/**
 * Icon config for the delivery map markers (Phase 8). PNGs are generated by
 * scripts/generate-markers.mjs into src/assets/markers/. Rendered at 40×40 and
 * anchored at the centre so the disc sits on the coordinate.
 */
export type MarkerName = 'shop' | 'destination' | 'rider';

export const markerIcon = (name: MarkerName) => ({
  iconUrl: `assets/markers/${name}.png`,
  iconSize: { width: 40, height: 40 },
  iconOrigin: { x: 0, y: 0 },
  iconAnchor: { x: 20, y: 20 },
});
